#!/bin/sh
# -*-shell-*-

BUCKET=$1
REGION=$2

aws s3 ls --region ${REGION} s3://${BUCKET}/bundles/ | grep '\-latest' | while read BUNDLE
do

    YMD=`echo ${BUNDLE} | awk '{ print $1 }' | sed s/-//g`
    HMS=`echo ${BUNDLE} | awk '{ print $2 }' | sed s/://g`

    DT="${YMD}T${HMS}"

    LATEST=`echo ${BUNDLE} | awk '{ print $4 }'`
    DATED=`echo ${LATEST} | sed s/-latest/-${DT}/`

    aws s3 --region ${REGION} cp s3://${BUCKET}/bundles/${LATEST} s3://${BUCKET}/bundles/${DATED} 
done
